#!/usr/bin/env php
<?php
include('class/User.php');

try {
    $username = $argv[1];
    $publicKey = (new User($username))
        ->loadSSHPublicKeyId()
        ->loadSSHPublicKey()
        ->getSSHPublicKey();
    echo $publicKey;
} catch (Exception $e) {
    $error = $e->getMessage();
    error_log(date('Y-m-d H:s:i')." $error\n", 3, "/tmp/ec2loginmanager".date('ymd').".log");
}
